import { createSlice } from "@reduxjs/toolkit";
import { fetchNews } from "./actions.js";

const initialState = {
  all: [],
  loading: false,
};

export const newsSlice = createSlice({
  name: "news",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchNews.pending, (state) => {
        state.loading = true;
      })
      .addCase(fetchNews.fulfilled, (state, action) => {
        const { articles } = action.payload;
        state.all = [...articles];
        state.loading = false;
      })
      .addCase(fetchNews.rejected, (state) => {
        state.loading = false;
      });
  },
});


export default newsSlice.reducer;
